[package]
name = "gfx_window_shared"
version = "0.2.0"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[dependencies]
gfx = "0.7"
gfx_device_gl = "0.5"
pistoncore-window = "0.9.1"

[dev-dependencies]
glutin = "*"
pistoncore-glutin_window = "0.12.0"
pistoncore-input = "*"
shader_version = "*"
