[package]
name = "gfx_window_shared"
version = "0.1.0"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[dependencies]
gfx = "0.6"
gfx_device_gl = "0.4"
pistoncore-window = "0.1"

[dev-dependencies]
glutin = "0.1"
pistoncore-glutin_window = "0.1"
pistoncore-input = "0.1"
shader_version = "0.1"
